name: ansible_test
on:
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        
#       - name: Install Python dependencies
#         uses: py-actions/py-dependency-install@v3
#         with:
#           path: test-requirements.txt
        
      - name: Perform unit testing with ansible-test for python37
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.11
          python-version: ${{ matrix.python }}
          target-python-version: ${{ matrix.python }}
          testing-type: units
          test-deps: >-
            ansible.netcommon
            ansible.utils
