---
# push workflow is shared and expected to perform actions after a merge happens
# on a maintenance branch (default or release). For example updating the
# draft release-notes.
# based on great work from
# https://github.com/T-Systems-MMS/ansible-collection-icinga-director
name: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
env:
  NAMESPACE: ansible
  COLLECTION_NAME: yang
  ANSIBLE_COLLECTIONS_PATHS: ./

jobs:
  update_release_draft:
    uses: ansible/ansible-content-actions/.github/workflows/draft_release.yaml@main
    with:
      repo: ${{ github.event.pull_request.head.repo.full_name }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
